# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Weather integration
weather:
  - platform: met
    name: Home

# Lovelace Configuration
lovelace:
  mode: yaml
  dashboards:
    lovelace-weather:
      mode: yaml
      title: Weather Dashboard
      icon: mdi:weather-partly-cloudy
      show_in_sidebar: true
      filename: dashboards/weather.yaml

strava:
  client_id: !secret strava_client_id
  client_secret: !secret strava_client_secret
