title: Home Dashboard
views:
  - title: Overview
    path: home
    icon: mdi:home
    cards:
      - type: weather-forecast
        entity: weather.forecast_home
        name: Current Weather
      - type: entities
        title: Quick Access
        entities:
          - entity: sun.sun
          - entity: sensor.date
          - entity: sensor.time
      - type: glance
        title: House Status
        entities:
          - entity: binary_sensor.front_door
          - entity: sensor.outside_temperature
          - entity: sensor.house_power_consumption
          - entity: sensor.water_consumption

  - title: Power Usage
    path: power
    icon: mdi:lightning-bolt
    cards:
      - type: energy-distribution
        title: Energy Distribution
      - type: energy-usage-graph
        title: Energy Usage Over Time
      - type: entities
        title: Power Consumption
        entities:
          - entity: sensor.total_power_consumption
          - entity: sensor.solar_production
          - entity: sensor.grid_consumption
      - type: custom:power-flow-card
        title: Power Flow
      - type: custom:mini-graph-card
        title: Daily Usage
        entities:
          - entity: sensor.daily_energy_consumption
        hours_to_show: 24

  - title: Water
    path: water
    icon: mdi:water
    cards:
      - type: custom:mini-graph-card
        title: Water Usage
        entities:
          - entity: sensor.water_consumption
        hours_to_show: 24
      - type: entities
        title: Water Metrics
        entities:
          - entity: sensor.water_pressure
          - entity: sensor.water_flow_rate
          - entity: sensor.daily_water_usage
      - type: custom:apexcharts-card
        title: Monthly Water Usage
        graph: bar
        entities:
          - entity: sensor.monthly_water_consumption

  - title: Security
    path: security
    icon: mdi:security
    cards:
      # Doorbell Camera
      - type: picture-entity
        title: Doorbell
        entity: camera.front_door_doorbell
        camera_view: live
        show_state: false
        show_name: true
      
      # Driveway Camera
      - type: picture-entity
        title: Driveway
        entity: camera.driveway
        camera_view: live
        show_state: false
        show_name: true

      # Front Yard Camera
      - type: picture-entity
        title: Front Yard
        entity: camera.front_yard
        camera_view: live
        show_state: false
        show_name: true

      # Back Yard Camera
      - type: picture-entity
        title: Back Yard
        entity: camera.backyard
        camera_view: live
        show_state: false
        show_name: true

      # Camera Grid View
      - type: grid
        title: All Cameras
        cards:
          - type: picture-entity
            entity: camera.front_door_doorbell
            name: Doorbell
          - type: picture-entity
            entity: camera.driveway
            name: Driveway
          - type: picture-entity
            entity: camera.front_yard
            name: Front Yard
          - type: picture-entity
            entity: camera.backyard
            name: Back Yard

      # Motion Events
      - type: history-graph
        title: Camera Motion Events
        entities:
          - entity: binary_sensor.front_door_doorbell_motion
          - entity: binary_sensor.driveway_motion
          - entity: binary_sensor.front_yard_motion
          - entity: binary_sensor.backyard_motion

  - title: Lighting
    path: lighting
    icon: mdi:lightbulb-group
    cards:
      - type: light
        title: Living Room
        entity: light.living_room
      - type: entities
        title: Indoor Lights
        entities:
          - entity: light.kitchen
          - entity: light.dining_room
          - entity: light.bedroom
          - entity: light.bathroom
      - type: entities
        title: Outdoor Lights
        entities:
          - entity: light.porch
          - entity: light.garage
          - entity: light.backyard
      - type: custom:light-entity-card
        title: Light Controls
        entity: light.living_room
      - type: custom:mushroom-light-card
        title: Scene Controls
        entities:
          - entity: scene.morning
          - entity: scene.evening
          - entity: scene.movie

resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
    