title: Home Dashboard
views:
  - !include lovelace/views/overview.yaml
  - !include lovelace/views/power.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/water.yaml
  - !include lovelace/views/fitness.yaml

resources: !include_dir_list resources
