title: Home Dashboard
views:
  - title: Overview
    path: home
    icon: mdi:home
    cards:
      - type: weather-forecast
        entity: weather.forecast_home
        name: Current Weather
      - type: entities
        title: Quick Access
        entities:
          - entity: sun.sun
          - entity: sensor.date
          - entity: sensor.time
      - type: glance
        title: House Status
        entities:
          - entity: binary_sensor.front_door
          - entity: sensor.outside_temperature
          - entity: sensor.house_power_consumption
          - entity: sensor.water_consumption

  - title: Power Usage
    path: power
    icon: mdi:lightning-bolt
    cards:
      # Weekly Power Consumption Overview
      - type: custom:apexcharts-card
        title: Last Week Power Usage
        graph: line
        span:
          start: week
        header:
          show: true
          title: Weekly Power Consumption
        series:
          - entity: sensor.span_total_power
            name: Total House Power
            stroke_width: 2
            curve: smooth

      # Top Power Consuming Circuits
      - type: custom:auto-entities
        card:
          type: custom:mini-graph-card
          title: Top 5 Power Consuming Circuits
          hours_to_show: 168  # 1 week
          group_by: date
          aggregate_func: max
          show:
            graph: bar
            legend: true
            name: true
            state: true
        filter:
          include:
            - domain: sensor
              attributes:
                device_class: power
              entity_id: "/^sensor.span_circuit.*_power/"
          sort:
            method: state
            numeric: true
            descending: true
          limit: 5

      # Solar Production
      - type: custom:apexcharts-card
        title: Solar Production
        graph: area
        span:
          start: week
        series:
          - entity: sensor.span_solar_production
            name: Solar Production
            color: '#ffd700'
            show:
              in_chart: true
              header_color: true
        header:
          show: true
          title: Weekly Solar Production

      # Current Power Flow
      - type: custom:power-flow-card
        title: Live Power Flow
        entities:
          grid:
            consumption: sensor.span_grid_consumption
            production: sensor.span_grid_production
          solar:
            production: sensor.span_solar_production
          home:
            consumption: sensor.span_total_power

      # Daily Overview
      - type: entities
        title: Today's Overview
        entities:
          - entity: sensor.span_total_power
            name: Current House Usage
          - entity: sensor.span_solar_production
            name: Current Solar Production
          - entity: sensor.span_daily_consumption
            name: Today's Consumption
          - entity: sensor.span_daily_solar_production
            name: Today's Solar Production

  - title: Water
    path: water
    icon: mdi:water
    cards:
      - type: custom:mini-graph-card
        title: Water Usage
        entities:
          - entity: sensor.water_consumption
        hours_to_show: 24
      - type: entities
        title: Water Metrics
        entities:
          - entity: sensor.water_pressure
          - entity: sensor.water_flow_rate
          - entity: sensor.daily_water_usage
      - type: custom:apexcharts-card
        title: Monthly Water Usage
        graph: bar
        entities:
          - entity: sensor.monthly_water_consumption

  - title: Security
    path: security
    icon: mdi:security
    cards:
      # Doorbell Camera
      - type: picture-entity
        title: Doorbell
        entity: camera.front_door_doorbell
        camera_view: live
        show_state: false
        show_name: true
      
      # Driveway Camera
      - type: picture-entity
        title: Driveway
        entity: camera.driveway
        camera_view: live
        show_state: false
        show_name: true

      # Front Yard Camera
      - type: picture-entity
        title: Front Yard
        entity: camera.front_yard
        camera_view: live
        show_state: false
        show_name: true

      # Back Yard Camera
      - type: picture-entity
        title: Back Yard
        entity: camera.backyard
        camera_view: live
        show_state: false
        show_name: true

      # Camera Grid View
      - type: grid
        title: All Cameras
        cards:
          - type: picture-entity
            entity: camera.front_door_doorbell
            name: Doorbell
          - type: picture-entity
            entity: camera.driveway
            name: Driveway
          - type: picture-entity
            entity: camera.front_yard
            name: Front Yard
          - type: picture-entity
            entity: camera.backyard
            name: Back Yard

      # Motion Events
      - type: history-graph
        title: Camera Motion Events
        entities:
          - entity: binary_sensor.front_door_doorbell_motion
          - entity: binary_sensor.driveway_motion
          - entity: binary_sensor.front_yard_motion
          - entity: binary_sensor.backyard_motion

  - title: Lighting
    path: lighting
    icon: mdi:lightbulb-group
    cards:
      - type: light
        title: Living Room
        entity: light.living_room
      - type: entities
        title: Indoor Lights
        entities:
          - entity: light.kitchen
          - entity: light.dining_room
          - entity: light.bedroom
          - entity: light.bathroom
      - type: entities
        title: Outdoor Lights
        entities:
          - entity: light.porch
          - entity: light.garage
          - entity: light.backyard
      - type: custom:light-entity-card
        title: Light Controls
        entity: light.living_room
      - type: custom:mushroom-light-card
        title: Scene Controls
        entities:
          - entity: scene.morning
          - entity: scene.evening
          - entity: scene.movie

resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
    