title: Home Dashboard
views:
  - !include lovelace/views/overview.yaml
  - !include lovelace/views/power.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/water.yaml
  - !include lovelace/views/fitness.yaml
  - !include lovelace/views/network.yaml
  - !include lovelace/views/finance.yaml
  - !include lovelace/views/pool.yaml
  - !include lovelace/views/media.yaml

# resources: !include_dir_list resources
resources:
  - url: /hacsfiles/Home-Assistant-Lovelace-HTML-Jinja2-Template-card/html-template-card.js
    type: module
  - url: /hacsfiles/apexcharts-card/apexcharts-card.js
    type: module
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
  - url: /hacsfiles/ha-map-card/map-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/power-flow-card-plus/power-flow-card-plus.js
    type: module
  - url: /hacsfiles/weather-card/dist/weather-card.min.js
    type: module
  - url: /hacsfiles/spotify-card/spotify-card.js
    type: module